#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.6.7+ on Wed Feb 26 19:24:32 2014
#

import wx

# begin wxGlade: dependencies
import gettext
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MyFrame2(wx.Frame):
	
	def __init__(self, *args, **kwds):
		# begin wxGlade: MyFrame2.__init__
		kwds["style"] = wx.DEFAULT_FRAME_STYLE
		wx.Frame.__init__(self, *args, **kwds)
		tree = self.tree_ctrl_1 = wx.TreeCtrl(self, wx.ID_ANY, style=wx.TR_HAS_BUTTONS | wx.TR_DEFAULT_STYLE | wx.SUNKEN_BORDER)

		root = self.tree_ctrl_1.AddRoot('root')
		tree.SetItemHasChildren(root)
		tree.AppendItem(root, "test")
		
		self.panel_3 = wx.Panel(self, wx.ID_ANY)

		menuBar = MenuBar()
		self.SetMenuBar(menuBar)
		
		self.__set_properties()
		self.__do_layout()
		# end wxGlade

	def __set_properties(self):
		# begin wxGlade: MyFrame2.__set_properties
		self.SetTitle(_("frame_3"))
		self.SetSize((800, 600))
		self.panel_3.SetMinSize((700, 600))
		# end wxGlade

	def __do_layout(self):
		# begin wxGlade: MyFrame2.__do_layout
		sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
		sizer_4.Add(self.tree_ctrl_1, 1, wx.EXPAND, 0)
		sizer_4.Add(self.panel_3, 1, wx.EXPAND, 0)
		self.SetSizer(sizer_4)
		self.Layout()
		# end wxGlade

# end of class MyFrame2

class MenuBar(wx.MenuBar):
	
	def __init__(self, *args, **kwds):
		# begin wxGlade: MenuBar.__init__
		wx.MenuBar.__init__(self, *args, **kwds)
		self.File = wx.Menu()
		self.File.Append(wx.ID_ANY, _("Open"), "", wx.ITEM_NORMAL)
		self.File.Append(wx.ID_ANY, _("Save"), "", wx.ITEM_NORMAL)
		self.File.Append(wx.ID_ANY, _("Close"), "", wx.ITEM_NORMAL)
		self.Append(self.File, _("File"))
		self.About = wx.Menu()
		self.Append(self.About, _("About"))
		self.FaQ = wx.Menu()
		self.Append(self.FaQ, _("FaQ"))

		self.__set_properties()
		self.__do_layout()
		# end wxGlade

	def __set_properties(self):
		# begin wxGlade: MenuBar.__set_properties
		pass
		# end wxGlade

	def __do_layout(self):
		# begin wxGlade: MenuBar.__do_layout
		pass
		# end wxGlade

# end of class MenuBar
if __name__ == "__main__":
	gettext.install("app") # replace with the appropriate catalog name

	app = wx.PySimpleApp(0)
	wx.InitAllImageHandlers()
	frame_3 = MyFrame2(None, wx.ID_ANY, "")
	app.SetTopWindow(frame_3)
	frame_3.Show()
	app.MainLoop()
